apiVersion: v1
stringData:
  mlmd_config.prototxt: |
    connection_config: <
      mysql: <
        host: "mysql"
        port: 3306
        database: "metadb"
        user: "root"
        password: "{{password}}"
      >
    >
kind: Secret
metadata:
  labels:
    component: metadata-server
  name: mlmd-config
  namespace: kubeflow