FROM gcr.io/deeplearning-platform-release/pytorch-cpu.1-1
RUN PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip \
&& curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/$PROTOC_ZIP \
&& unzip -o $PROTOC_ZIP -d /usr/local bin/protoc \
&& unzip -o $PROTOC_ZIP -d /usr/local include/* \
&& rm -f $PROTOC_ZIP 
RUN git clone https://github.com/tensorflow/tfx.git -b r0.14 \
&& cd tfx \
&& python setup.py sdist \
&& pip install dist/* 


