resources:
  - github.com/kubeflow/pipelines//manifests/kustomize/namespaced/?ref=master
  - github.com/kubeflow/pipelines//manifests/kustomize/env/gcp/minio/?ref=master
  - github.com/kubeflow/pipelines//manifests/kustomize/env/gcp/mysql/?ref=master

namespace: kubeflow

images:
  - name: gcr.io/cloudsql-docker/gce-proxy
    newTag: "1.14"
  - name: gcr.io/ml-pipeline/minio
    newTag: RELEASE.2019-08-14T20-37-41Z

patchesStrategicMerge:
  - cloudsqlproxy-patch.yaml
  - ml-pipeline-patch.yaml
  - mysql-secret-patch.yaml


configMapGenerator:
  - name: gcp-configs
    env: gcp-configs.env