resources:
  - github.com/kubeflow/pipelines//manifests/kustomize/namespaced/?ref=0.1.32
  - github.com/kubeflow/pipelines//manifests/kustomize/env/gcp/minio/?ref=0.1.32
  - github.com/kubeflow/pipelines//manifests/kustomize/env/gcp/mysql/?ref=0.1.32

namespace: kubeflow

images:
  - name: gcr.io/cloudsql-docker/gce-proxy
    newTag: "1.14"
  - name: gcr.io/ml-pipeline/minio
    newTag: RELEASE.2019-08-14T20-37-41Z-license-compliance

patchesStrategicMerge:
  - cloudsqlproxy-patch.yaml
  - ml-pipeline-patch.yaml
  
configMapGenerator:
  - name: gcp-configs
    env: gcp-configs.env

secretGenerator:
  - name: user-gcp-sa
    files:
      - application_default_credentials.json