---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlmd-service-configmap
data:
  mlmd_config.prototxt: |
    connection_config: <
      mysql: <
        host: "mysql"
        port: 3306
        database: "metadb"
        user: "root"
        password: "victoria2020"
      >
    >
