apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - name: OBJECTSTORECONFIG_BUCKETNAME
              # Don't add gs:// prefix.
              # If bucket doesn't exist, the deployment will create one.
              value: 'kfp-sandbox'
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  template:
    spec:
      containers:
        - name: cloudsqlproxy
          env:
            - name: CLOUD_SQL_INSTANCE_CONNECTION_NAME
              # E.g. project-id:us-central1:instance-name
              value: 'jk-demo1:us-central1:jksql2'
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: metadata-deployment
  namespace: kubeflow
spec:
  template:
    spec:
     volumes:
      - name: mlmd-server-config-volume
        secret:
          secretName: mlmd-config
        configMap: null
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: mlmd-service-configmap
#$patch: delete