apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  template:
    spec:
      containers:
        - name: cloudsqlproxy
          env:
            - name: CLOUD_SQL_INSTANCE_CONNECTION_NAME
              valueFrom: 
                configMapKeyRef:
                  name: gcp-configs
                  key: connection_name