resources:
  - github.com/kubeflow/pipelines//manifests/kustomize/namespaced/?ref=0.1.29
  - github.com/kubeflow/pipelines//manifests/kustomize/env/gcp/minio/?ref=0.1.29
  - github.com/kubeflow/pipelines//manifests/kustomize/env/gcp/mysql/?ref=0.1.29

namespace: kubeflow

images:
  - name: gcr.io/cloudsql-docker/gce-proxy
    newTag: "1.14"
  - name: gcr.io/ml-pipeline/minio
    newTag: RELEASE.2019-08-14T20-37-41Z

patchesStrategicMerge:
  - cloudsqlproxy-patch.yaml
  - ml-pipeline-patch.yaml
  - ml-metadata-patch.yaml

secretGenerator:
  - name: user-gcp-sa
    files: 
      - secrets_and_configs/application_default_credentials.json
    type: Opaque
  - name: cloudsql-config
    env: secrets_and_configs/cloudsql_config.txt
    type: Opaque
  - name: mlmd-config
    files:
      - secrets_and_configs/mlmd_config.prototxt
    type: Opaque

configMapGenerator:
  - name: objectstore-config
    env: secrets_and_configs/objectstore_config.txt