apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Constructs a Kubeflow
      pipeline.\n\n      Creates Kubeflow ContainerOps for each TFX component encountered
      in the\n      logical pipeline definition.\n      ", "name": "chicago_taxi_kfp"}'
  generateName: chicago-taxi-kfp-
spec:
  arguments:
    parameters: []
  entrypoint: chicago-taxi-kfp
  serviceAccountName: pipeline-runner
  templates:
  - container:
      args:
      - --pipeline_name
      - chicago_taxi_kfp
      - --pipeline_root
      - gs://caip_tfx/chicago_taxi_kfp
      - --kubeflow_metadata_config
      - "{\n  \"mysqlDbServiceHost\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_HOST\"\
        \n  },\n  \"mysqlDbServicePort\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_PORT\"\
        \n  },\n  \"mysqlDbName\": {\n    \"value\": \"metadb\"\n  },\n  \"mysqlDbUser\"\
        : {\n    \"environmentVariable\": \"MYSQL_USERNAME\"\n  },\n  \"mysqlDbPassword\"\
        : {\n    \"environmentVariable\": \"MYSQL_PASSWORD\"\n  }\n}"
      - --additional_pipeline_args
      - '{"gcs_path": "gs://caip-tfx"}'
      - --component_id
      - BigQueryExampleGen
      - --component_type
      - tfx.components.example_gen.big_query_example_gen.component.BigQueryExampleGen
      - --driver_class_path
      - tfx.components.base.base_driver.BaseDriver
      - --executor_spec
      - '{"__class__": "ExecutorClassSpec", "__module__": "tfx.components.base.executor_spec",
        "__tfx_object_type__": "jsonable", "executor_class": {"__class__": "Executor",
        "__module__": "tfx.components.example_gen.big_query_example_gen.executor",
        "__tfx_object_type__": "class"}}'
      - --inputs
      - '{}'
      - --outputs
      - '{"examples": [{"artifact": {"properties": {"split": {"stringValue": "train"},
        "producer_component": {"stringValue": "BigQueryExampleGen"}, "pipeline_name":
        {"stringValue": "chicago_taxi_kfp"}, "name": {"stringValue": "examples"},
        "type_name": {"stringValue": "ExamplesPath"}}}, "artifact_type": {"name":
        "ExamplesPath", "properties": {"name": "STRING", "type_name": "STRING", "state":
        "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name":
        "STRING", "split": "STRING"}}}, {"artifact": {"properties": {"producer_component":
        {"stringValue": "BigQueryExampleGen"}, "pipeline_name": {"stringValue": "chicago_taxi_kfp"},
        "name": {"stringValue": "examples"}, "type_name": {"stringValue": "ExamplesPath"},
        "split": {"stringValue": "eval"}}}, "artifact_type": {"name": "ExamplesPath",
        "properties": {"type_name": "STRING", "state": "STRING", "producer_component":
        "STRING", "span": "INT", "pipeline_name": "STRING", "split": "STRING", "name":
        "STRING"}}}]}'
      - --exec_properties
      - '{"input_config": "{\n  \"splits\": [\n    {\n      \"name\": \"single_split\",\n      \"pattern\":
        \"\\n         SELECT\\n           pickup_community_area,\\n           fare,\\n           EXTRACT(MONTH
        FROM trip_start_timestamp) AS trip_start_month,\\n           EXTRACT(HOUR
        FROM trip_start_timestamp) AS trip_start_hour,\\n           EXTRACT(DAYOFWEEK
        FROM trip_start_timestamp) AS trip_start_day,\\n           UNIX_SECONDS(trip_start_timestamp)
        AS trip_start_timestamp,\\n           pickup_latitude,\\n           pickup_longitude,\\n           dropoff_latitude,\\n           dropoff_longitude,\\n           trip_miles,\\n           pickup_census_tract,\\n           dropoff_census_tract,\\n           payment_type,\\n           company,\\n           trip_seconds,\\n           dropoff_community_area,\\n           tips\\n         FROM
        `bigquery-public-data.chicago_taxi_trips.taxi_trips`\\n         WHERE (ABS(FARM_FINGERPRINT(unique_key))
        / 0x7FFFFFFFFFFFFFFF)\\n           < 0.001\"\n    }\n  ]\n}", "output_config":
        "{\n  \"splitConfig\": {\n    \"splits\": [\n      {\n        \"hashBuckets\":
        2,\n        \"name\": \"train\"\n      },\n      {\n        \"hashBuckets\":
        1,\n        \"name\": \"eval\"\n      }\n    ]\n  }\n}", "custom_config":
        null}'
      command:
      - python
      - /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py
      env:
      - name: WORKFLOW_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['workflows.argoproj.io/workflow']
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: MYSQL_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: mysql-credential
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-credential
      image: tensorflow/tfx:0.14.0
      volumeMounts:
      - mountPath: /secret/gcp-credentials
        name: gcp-credentials-user-gcp-sa
    name: bigqueryexamplegen
  - dag:
      tasks:
      - name: bigqueryexamplegen
        template: bigqueryexamplegen
      - dependencies:
        - schemagen
        - statisticsgen
        name: examplevalidator
        template: examplevalidator
      - dependencies:
        - statisticsgen
        name: schemagen
        template: schemagen
      - dependencies:
        - bigqueryexamplegen
        name: statisticsgen
        template: statisticsgen
    name: chicago-taxi-kfp
  - container:
      args:
      - --pipeline_name
      - chicago_taxi_kfp
      - --pipeline_root
      - gs://caip_tfx/chicago_taxi_kfp
      - --kubeflow_metadata_config
      - "{\n  \"mysqlDbServiceHost\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_HOST\"\
        \n  },\n  \"mysqlDbServicePort\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_PORT\"\
        \n  },\n  \"mysqlDbName\": {\n    \"value\": \"metadb\"\n  },\n  \"mysqlDbUser\"\
        : {\n    \"environmentVariable\": \"MYSQL_USERNAME\"\n  },\n  \"mysqlDbPassword\"\
        : {\n    \"environmentVariable\": \"MYSQL_PASSWORD\"\n  }\n}"
      - --additional_pipeline_args
      - '{"gcs_path": "gs://caip-tfx"}'
      - --component_id
      - ExampleValidator
      - --component_type
      - tfx.components.example_validator.component.ExampleValidator
      - --driver_class_path
      - tfx.components.base.base_driver.BaseDriver
      - --executor_spec
      - '{"__class__": "ExecutorClassSpec", "__module__": "tfx.components.base.executor_spec",
        "__tfx_object_type__": "jsonable", "executor_class": {"__class__": "Executor",
        "__module__": "tfx.components.example_validator.executor", "__tfx_object_type__":
        "class"}}'
      - --inputs
      - '{"stats": [{"artifact": {"properties": {"split": {"stringValue": "train"},
        "producer_component": {"stringValue": "StatisticsGen"}, "pipeline_name": {"stringValue":
        "chicago_taxi_kfp"}, "name": {"stringValue": "output"}, "type_name": {"stringValue":
        "ExampleStatisticsPath"}}}, "artifact_type": {"name": "ExampleStatisticsPath",
        "properties": {"name": "STRING", "type_name": "STRING", "state": "STRING",
        "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING",
        "split": "STRING"}}}, {"artifact": {"properties": {"type_name": {"stringValue":
        "ExampleStatisticsPath"}, "split": {"stringValue": "eval"}, "producer_component":
        {"stringValue": "StatisticsGen"}, "pipeline_name": {"stringValue": "chicago_taxi_kfp"},
        "name": {"stringValue": "output"}}}, "artifact_type": {"name": "ExampleStatisticsPath",
        "properties": {"split": "STRING", "name": "STRING", "type_name": "STRING",
        "state": "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name":
        "STRING"}}}], "schema": [{"artifact": {"properties": {"name": {"stringValue":
        "output"}, "type_name": {"stringValue": "SchemaPath"}, "split": {"stringValue":
        ""}, "producer_component": {"stringValue": "SchemaGen"}, "pipeline_name":
        {"stringValue": "chicago_taxi_kfp"}}}, "artifact_type": {"name": "SchemaPath",
        "properties": {"name": "STRING", "type_name": "STRING", "state": "STRING",
        "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING",
        "split": "STRING"}}}]}'
      - --outputs
      - '{"output": [{"artifact": {"properties": {"name": {"stringValue": "output"},
        "type_name": {"stringValue": "ExampleValidationPath"}, "split": {"stringValue":
        ""}, "producer_component": {"stringValue": "ExampleValidator"}, "pipeline_name":
        {"stringValue": "chicago_taxi_kfp"}}}, "artifact_type": {"name": "ExampleValidationPath",
        "properties": {"name": "STRING", "type_name": "STRING", "state": "STRING",
        "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING",
        "split": "STRING"}}}]}'
      - --exec_properties
      - '{}'
      command:
      - python
      - /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py
      env:
      - name: WORKFLOW_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['workflows.argoproj.io/workflow']
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: MYSQL_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: mysql-credential
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-credential
      image: tensorflow/tfx:0.14.0
      volumeMounts:
      - mountPath: /secret/gcp-credentials
        name: gcp-credentials-user-gcp-sa
    name: examplevalidator
  - container:
      args:
      - --pipeline_name
      - chicago_taxi_kfp
      - --pipeline_root
      - gs://caip_tfx/chicago_taxi_kfp
      - --kubeflow_metadata_config
      - "{\n  \"mysqlDbServiceHost\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_HOST\"\
        \n  },\n  \"mysqlDbServicePort\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_PORT\"\
        \n  },\n  \"mysqlDbName\": {\n    \"value\": \"metadb\"\n  },\n  \"mysqlDbUser\"\
        : {\n    \"environmentVariable\": \"MYSQL_USERNAME\"\n  },\n  \"mysqlDbPassword\"\
        : {\n    \"environmentVariable\": \"MYSQL_PASSWORD\"\n  }\n}"
      - --additional_pipeline_args
      - '{"gcs_path": "gs://caip-tfx"}'
      - --component_id
      - SchemaGen
      - --component_type
      - tfx.components.schema_gen.component.SchemaGen
      - --driver_class_path
      - tfx.components.base.base_driver.BaseDriver
      - --executor_spec
      - '{"__class__": "ExecutorClassSpec", "__module__": "tfx.components.base.executor_spec",
        "__tfx_object_type__": "jsonable", "executor_class": {"__class__": "Executor",
        "__module__": "tfx.components.schema_gen.executor", "__tfx_object_type__":
        "class"}}'
      - --inputs
      - '{"stats": [{"artifact": {"properties": {"split": {"stringValue": "train"},
        "producer_component": {"stringValue": "StatisticsGen"}, "pipeline_name": {"stringValue":
        "chicago_taxi_kfp"}, "name": {"stringValue": "output"}, "type_name": {"stringValue":
        "ExampleStatisticsPath"}}}, "artifact_type": {"name": "ExampleStatisticsPath",
        "properties": {"name": "STRING", "type_name": "STRING", "state": "STRING",
        "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING",
        "split": "STRING"}}}, {"artifact": {"properties": {"type_name": {"stringValue":
        "ExampleStatisticsPath"}, "split": {"stringValue": "eval"}, "producer_component":
        {"stringValue": "StatisticsGen"}, "pipeline_name": {"stringValue": "chicago_taxi_kfp"},
        "name": {"stringValue": "output"}}}, "artifact_type": {"name": "ExampleStatisticsPath",
        "properties": {"split": "STRING", "name": "STRING", "type_name": "STRING",
        "state": "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name":
        "STRING"}}}]}'
      - --outputs
      - '{"output": [{"artifact": {"properties": {"name": {"stringValue": "output"},
        "type_name": {"stringValue": "SchemaPath"}, "split": {"stringValue": ""},
        "producer_component": {"stringValue": "SchemaGen"}, "pipeline_name": {"stringValue":
        "chicago_taxi_kfp"}}}, "artifact_type": {"name": "SchemaPath", "properties":
        {"name": "STRING", "type_name": "STRING", "state": "STRING", "producer_component":
        "STRING", "span": "INT", "pipeline_name": "STRING", "split": "STRING"}}}]}'
      - --exec_properties
      - '{"infer_feature_shape": false}'
      command:
      - python
      - /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py
      env:
      - name: WORKFLOW_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['workflows.argoproj.io/workflow']
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: MYSQL_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: mysql-credential
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-credential
      image: tensorflow/tfx:0.14.0
      volumeMounts:
      - mountPath: /secret/gcp-credentials
        name: gcp-credentials-user-gcp-sa
    name: schemagen
  - container:
      args:
      - --pipeline_name
      - chicago_taxi_kfp
      - --pipeline_root
      - gs://caip_tfx/chicago_taxi_kfp
      - --kubeflow_metadata_config
      - "{\n  \"mysqlDbServiceHost\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_HOST\"\
        \n  },\n  \"mysqlDbServicePort\": {\n    \"environmentVariable\": \"MYSQL_SERVICE_PORT\"\
        \n  },\n  \"mysqlDbName\": {\n    \"value\": \"metadb\"\n  },\n  \"mysqlDbUser\"\
        : {\n    \"environmentVariable\": \"MYSQL_USERNAME\"\n  },\n  \"mysqlDbPassword\"\
        : {\n    \"environmentVariable\": \"MYSQL_PASSWORD\"\n  }\n}"
      - --additional_pipeline_args
      - '{"gcs_path": "gs://caip-tfx"}'
      - --component_id
      - StatisticsGen
      - --component_type
      - tfx.components.statistics_gen.component.StatisticsGen
      - --driver_class_path
      - tfx.components.base.base_driver.BaseDriver
      - --executor_spec
      - '{"__class__": "ExecutorClassSpec", "__module__": "tfx.components.base.executor_spec",
        "__tfx_object_type__": "jsonable", "executor_class": {"__class__": "Executor",
        "__module__": "tfx.components.statistics_gen.executor", "__tfx_object_type__":
        "class"}}'
      - --inputs
      - '{"input_data": [{"artifact": {"properties": {"split": {"stringValue": "train"},
        "producer_component": {"stringValue": "BigQueryExampleGen"}, "pipeline_name":
        {"stringValue": "chicago_taxi_kfp"}, "name": {"stringValue": "examples"},
        "type_name": {"stringValue": "ExamplesPath"}}}, "artifact_type": {"name":
        "ExamplesPath", "properties": {"name": "STRING", "type_name": "STRING", "state":
        "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name":
        "STRING", "split": "STRING"}}}, {"artifact": {"properties": {"producer_component":
        {"stringValue": "BigQueryExampleGen"}, "pipeline_name": {"stringValue": "chicago_taxi_kfp"},
        "name": {"stringValue": "examples"}, "type_name": {"stringValue": "ExamplesPath"},
        "split": {"stringValue": "eval"}}}, "artifact_type": {"name": "ExamplesPath",
        "properties": {"type_name": "STRING", "state": "STRING", "producer_component":
        "STRING", "span": "INT", "pipeline_name": "STRING", "split": "STRING", "name":
        "STRING"}}}]}'
      - --outputs
      - '{"output": [{"artifact": {"properties": {"split": {"stringValue": "train"},
        "producer_component": {"stringValue": "StatisticsGen"}, "pipeline_name": {"stringValue":
        "chicago_taxi_kfp"}, "name": {"stringValue": "output"}, "type_name": {"stringValue":
        "ExampleStatisticsPath"}}}, "artifact_type": {"name": "ExampleStatisticsPath",
        "properties": {"name": "STRING", "type_name": "STRING", "state": "STRING",
        "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING",
        "split": "STRING"}}}, {"artifact": {"properties": {"type_name": {"stringValue":
        "ExampleStatisticsPath"}, "split": {"stringValue": "eval"}, "producer_component":
        {"stringValue": "StatisticsGen"}, "pipeline_name": {"stringValue": "chicago_taxi_kfp"},
        "name": {"stringValue": "output"}}}, "artifact_type": {"name": "ExampleStatisticsPath",
        "properties": {"split": "STRING", "name": "STRING", "type_name": "STRING",
        "state": "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name":
        "STRING"}}}]}'
      - --exec_properties
      - '{}'
      command:
      - python
      - /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py
      env:
      - name: WORKFLOW_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['workflows.argoproj.io/workflow']
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
        value: /secret/gcp-credentials/user-gcp-sa.json
      - name: MYSQL_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: mysql-credential
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: mysql-credential
      image: tensorflow/tfx:0.14.0
      volumeMounts:
      - mountPath: /secret/gcp-credentials
        name: gcp-credentials-user-gcp-sa
    name: statisticsgen
  volumes:
  - name: gcp-credentials-user-gcp-sa
    secret:
      secretName: user-gcp-sa
