pipeline:
  name: chicago_taxi_4
  model_name: chicago_taxi_4
  training_image: gcr.io/jk-demo3/tfx_demo:latest
environment:
  project_id: jk-demo3
  region: us-central1
  artifact_store: gs://tfx-dev6-artifact-store